{% set version = "6.1.0" %}
{% set test_files_to_skip = " --ignore=tests/unit/test_format.py" %}
{% set test_files_to_skip = test_files_to_skip + " --ignore=tests/unit/test_pylama_isort.py" %}
{% set tests_to_skip = "test_requirements_dir" %}
{% set tests_to_skip = tests_to_skip + " or test_requirements_finder" %}
{% set tests_to_skip = tests_to_skip + " or test_git_hook" %}
{% set tests_to_skip = tests_to_skip + " or test_importable" %}
{% set tests_to_skip = tests_to_skip + " or test_module" %}
{% set tests_to_skip = tests_to_skip + " or test_isort_supports_shared_profiles_issue_970" %}
{% set tests_to_skip = tests_to_skip + " or test_sort_configurable_sort_issue_1732" %}
{% set tests_to_skip = tests_to_skip + " or test_gitignore" %}  # [not osx]

package:
  name: isort
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/isort/isort-{{ version }}.tar.gz
  sha256: 9b8f96a14cfee0677e78e941ff62f03769a06d412aabb9e2a90487b3b7e8d481

build:
  number: 0
  skip: true  # [py<390]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - isort = isort.main:main

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - importlib-metadata >=4.6.0  # [py<310]
  run_constrained:
    - colorama >=0.4.6

# Skipping tests since pylama is unavailable
# Skipping due to various errors
test:
  source_files:
    - tests/unit/
  imports:
    - isort
  commands:
    - pip check
    - isort --help
    - pytest tests/unit/ -v {{ test_files_to_skip }} -k "not({{ tests_to_skip }})"
  requires:
    - pip
    - pytest
    - anyio
    - coverage
    - exceptiongroup
    - hypothesis
    - psutil
    - pytest-mock
    - trustme
    - uvloop  # [unix]

about:
  home: https://github.com/timothycrosley/isort
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A Python utility / library to sort Python imports.
  description: |
    isort is a Python utility / library to sort imports alphabetically, and
    automatically separated into sections. It provides a command line utility,
    Python library and plugins for various editors to quickly sort all your
    imports. It currently cleanly supports Python 2.6 - 3.5 using pies to
    achieve this without ugly hacks and/or py2to3.
  doc_url: https://pycqa.github.io/isort/
  dev_url: https://github.com/timothycrosley/isort

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
    - nehaljwani
    - ocefpaf
