{% set name = "isort" %}
{% set version = "9.0.1" %}
{% set ignore_tests = " --ignore=tests/unit/test_pylama_isort.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/unit/profiles/test_black.py" %}  # [win and arm64]
{% set deselect_tests = " --deselect=tests/unit/test_importable.py::test_importable" %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/unit/test_hooks.py::test_git_hook"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/unit/test_place.py::test_module"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/unit/test_ticketed_features.py::test_isort_supports_shared_profiles_issue_970"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/unit/test_ticketed_features.py::test_sort_configurable_sort_issue_1732"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/unit/test_main.py::test_gitignore "' %}

# E   ModuleNotFoundError: No module named 'pylama'
# black module is unavailable on Windows ARM64, so we skip tests that require it
# >   raise InvalidSettingsPath(settings_path)
# E   isort.exceptions.InvalidSettingsPath: isort was told to use the settings_path: $SRC_DIR/isort as the base directory or file that represents the starting point of config file discovery, but it does not exist.
# >   assert place_tester("isort") == sections.FIRSTPARTY
# E   AssertionError: assert 'THIRDPARTY' == 'FIRSTPARTY'
# >   raise ProfileDoesNotExist(profile_name)
# E   isort.exceptions.ProfileDoesNotExist: Specified profile of example does not exist. Available profiles: black,django,pycharm,google,open_stack,plone,attrs,hug,wemake,appnexus.
# Test irrelevant for us (FileNotFoundError)
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba23db109e3e93ef1999f7209a651214994cd807801addd16ac485982eb4edd7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - isort = isort.main:main
    - isort-identify-imports = isort.main:identify_imports_main
  skip: true  # [py<3100]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - hatch-mypyc
  run:
    - python
    - mypy_extensions >=1.1.0

test:
  source_files:
    - tests/unit
  imports:
    - isort
  commands:
    - pip check
    - isort --help
    - isort-identify-imports --help
    - pytest -v tests/unit {{ ignore_tests }} {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - anyio
    - coverage
    - exceptiongroup
    - hypothesis
    - psutil
    - pytest-mock
    - trustme
    - uvloop  # [unix]
    - black  # [not (win and arm64)]
    - colorama
    - setuptools  # [py>=314]

about:
  home: https://github.com/timothycrosley/isort
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A Python utility / library to sort Python imports.
  description: |
    isort is a Python utility / library to sort imports alphabetically, and
    automatically separated into sections. It provides a command line utility,
    Python library and plugins for various editors to quickly sort all your
    imports. It currently cleanly supports Python 2.6 - 3.5 using pies to
    achieve this without ugly hacks and/or py2to3.
  doc_url: https://pycqa.github.io/isort
  dev_url: https://github.com/timothycrosley/isort

extra:
  recipe-maintainers:
    - goanpeca
    - nicoddemus
    - nehaljwani
    - ocefpaf
