travis:
  secure:
    BINSTAR_TOKEN: n9TC5ifwCUWWndIM4Bq43EaBZPq74gVBwPo2xGWXDKFvaazHzZyt/bUy8yIMOGi0pm4xDg03lTM3syMT7eYjDZ7fGVKE+I3yslRbzQARl2QvGZlWFaxmvftTXYGSEXhfHs65cwXu6FvyzYFQJudEFX0SmeSzXodglpdpa37Txma/oGX/SGi36RoyJ8KcfJ/Y13O9/w7ykokQDukixFtBZ5hostOU7IUoF4wwOTosdfuRZmRwtpgyYlIXQyqzvoQaGCVCSSBYGTpVT+ltIkI30CC1J7HCHTi+0G2EIHNbSh5c2CogSnuGg1nxg0fbBmkQicSuf+6IwiPw1TZOWSlz2KH6ylTOEbTi8lueKKogJLCXddsbzoLHDOkanE80Xw+2B3mlvAqpvDIVLsilyraxwylczCEaD0+Ck6ifkA740K0nm6fRj9mU2WT8svbzFB608lvRSxRAqzPncz+kZM75HX7EKWRnTAnus1nS0bvQFE6rJ9Zf5Hktx9VDtz65ejbcdX8NaKIOlyep+kM3ghqdssaDNJqkDvj7VHf/xMvWg9unrMQLhxteeYKJHY4sui2fYxPLgZZ+Z2+7RndWF6NptPIOyS1uKzA2C8na/KV+rKvvfZwHJsdkn8+nLOA864NVzqRv1lQxp1Ya7oxe9ZUhbju/dQoJ7FjepJ7ie0jSNgw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
