travis:
  secure:
    BINSTAR_TOKEN: B0d4sfgw1O2962u4AFY1+rAeJIuDRK/XH1v7BrPnyosM9JjEzG60RDl9VdxCfi33tmevhHxILQDgNrD4AcqSb1dl4ptUqF7z378OT0fzeKPuPE7AM0KSVquKp6+kFAO9tD6bwn5ReRwfKQgTJOq0nZnPGcA5W0FlfQDZ+G3qd2Z1o6h7GWYI9LB9oB9jNlUSupAblq5pqmB1V/rplsm5OETzMXC1+3Ea6E0lVyxd8xeJGMAOxrNePt43OUVHUqEPo0NXBUArV8TSb3+HQhyf8d4KPT8odafa9qGcgQ0otyitNkO7IKKHfNowl+wPRH+b3P/gNtcwvIZ7mRM19JVpjuGQbOf2vrD2k3SqUleGsK6bb/uFo+M5SMyDIBtl1Orl/RveMfkMxx8DPz+KKRUS6QS4QxwZfz8LEhlaWFqagn71h8g6WraDbcD4uyaR+kPuY+QoUa0p2ks9r5jy3aZIPM4YGc16kVz98h4Y3Rrb/J1XnaLBk2kwU0BgcBYjH8Ih9YiuF546jAHk8AkZYGhPagiBg1YMN9MsLC6+i2BpZcmo+lTiQeqzy0WgYpTl2D9hll0n3MnLDfw3rVuS0fRBePqkDwFxeaVy5TNi6R6fWke4Lwtjwt9ltW8HFNN5af2Utz9GBfJKJXAgGbI1bn50vIrIRA8Pil2njXtLtr/3pNM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
